### ISSUE TITLE
Auhtorization to dev.azure.com

### ISSUE THREAD

**Issue by huferry** [generalov/vscode-tfs#1]
How do I deal with this error (see image)?

![2019-08-06_13h05_53](https://user-images.githubusercontent.com/18510728/62535241-2c7da300-b84b-11e9-86fa-a65f11f4cd35.png)

**Comment by generalov** [comment]
Hi @huferry,
Main purpose of this extension is to support legacy versions of TFS in VS Code. It only works with existing TFS workspaces. A TFS workspace should exists on the local drive and tf.exe is working. Please check the output from tf.exe running in console for your workspace.

I believe that https://marketplace.visualstudio.com/items?itemName=ms-vsts.team extension should be preferred for Azure.
