### ISSUE TITLE
opening a folder from within a TFS repo doesnt register SCM provider

### ISSUE THREAD

**Issue by rocifier** [generalov/vscode-tfs#2]
Hi, I checked out my code locally from TFS using Visual Studio 2015. I then opened one of the folders in it for front-end development in vscode. When I go to the source control tab of vscode I see a single error in grey: "No source control providers registered."

Expected: Because I have installed TFS by Evgeniy Generalov and configured tfs.location to point to the visual studio 2015 tf.exe, I should see actions listed under the source control tab.

**Comment by generalov** [comment]
Hi @rocifier,
Thanks for the good idea. What actions would you like to see on the panel?

The official extension https://marketplace.visualstudio.com/items?itemName=ms-vsts.team provides some actions under the source control tab. Actually I use the both extensions.

**Comment by rocifier** [comment]
I guess I was expecting some of the equivalent basic commands as git so like seeing pending changes and being able to create change sets. So maybe I am looking for that official one? What would you say are the main differences? What does this extension do that the Microsoft one doesn’t? Cheers
