### ISSUE TITLE
Alt+T not working and doesn't seem to find TFS

### ISSUE THREAD

**Issue by tcsdmaic** [generalov/vscode-tfs#6]
I am using Visual Studio Code 1.44.2, and Visual Studio Professional 2019 16.3.10.
I set up TFS via Visual Studio Pro, through which I mapped my workspace, and then added a new branch to TFS, which is the folder I work out of.  All the TFS stuff in VS Pro works fine working out of this folder in my workspace.

In VS Code, I originally had "TFS 0.7.2" by Ivan Gabirele installed.  When I would newly open a file that is in my TFS and make changes then hit 'Save', it would tell me the file is read-only and I'd have to hit the 'Overwrite' button in order to save my changes, as expected.  But it seems that doing that didn't actually check out my file - I would go back to VS Pro into Source Control and it does not indicate that the file is checked out.  If I go to Pending Changes, it does not list anything.  Yet, if I do a compare of a changed file to my workspace it does show the changes I made.  In VS Code, I would hit Alt+T and go to Status, but it would give me an error:  "TFS: Unable to determine the source control server."

I figured I'd log this as an issue in GitHub, but found this project has been archived.  So, seeing that this one is actually a branch off of that and is not archived, I figured I'd try uninstalling that one, reloading VS Code, then (with VS Pro running as well) installed this TFS, and then reloaded VS Code.
I noticed that in the ReadMe there is an instruction to add the TFS path in Settings, so I did that, which ended up being "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\TF.exe"

Unfortunately, not only do I still experience the same behavior as with the other TFS extension, Alt+T opens the Terminal menu....NOT the TFS commands.  So I can't go to Status to see if that still gives me the same error.  A coworker is using the other TFS extension in VS Code with the same setup (working out of a branch he added) and it works fine for him, so we're not sure why I'm having issues.

**Comment by generalov** [comment]
Hello @tcsdmaic. There are to issues. The Status command is not implemented in this version of extension. Thanks for the idea.
The checkout on save functionality is not working properly with recent versions of VSCode. So I recommend to checkout a file manually (Ctrl + Shift + p -> TFS: Checkout) and wait a couple of seconds for a notification. After that the file will be unlocked for modifications.

**Comment by generalov** [comment]
I've added `Alt+T` keybinding and published new package. I use VS Pro for the status and checkin operations because it provides a convinient interface; not sure that this functionality will be implemented in this extension.
